import Head from "next/head";
import Image from "next/image";
import Link from 'next/link'

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Freediving School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
      <h1 className={styles.title}>
          Welcome to <a href="https://freediving-nicaragua.com">Freediving School</a>
        </h1>

        <p className={styles.description}>
          A comprehensive course on
          <code className={styles.code}>essential Freediving Skills.</code>
        </p>
        <div className={styles.grid}>

        <div className={styles.card}>
         <a href="/disciplines/general">GENERAL &rarr;</a>
        </div>  

        <div className={styles.card}>
         <a href="/disciplines/safety">SAFETY  &rarr;</a>
        </div>  

        <div className={styles.card}>
         <a href="/disciplines/cwt">CWT &rarr;</a>
        </div>

        <div className={styles.card}>
         <a href="/disciplines/static">STA  &rarr;</a>
        </div>                

        <div className={styles.card}>
         <a href="/disciplines/dynamic">DYN  &rarr;</a>
        </div>

        <div className={styles.card}>
         <a href="/disciplines/eq">EQ  &rarr;</a>
        </div>    
                 
        </div>
      </div>
      <footer className={styles.footer}>
          @Copyright 2023 Richard Angapin | All Right Reserved  
      </footer>
    </div>
  );
}
